### PR TITLE
Use accurate language.

### PR DESCRIPTION
**Pull request by emmajane**
Replace the term "slaving" with the more accurate descriptor "working hard".

### CODE REVIEW

**Comment by theofidry** [comment]
Do you feel like it is coming as offending here? It never bugged me as it comes as a joke and is a reference to our [devilish mascot](https://github.com/emmajane/humbug/blob/d9708b8dc75fda54519648b6b416b3999b71f6ba/README.md#bah-humbug. It is by no means to be interpreted literally or promote slavery.

**Comment by emmajane** [comment]
In my experience using positive, inclusive language makes people feel welcomed and more interested in using software. More to the point though: I don't see any harm in using accurate language, which is why I submitted the PR. So if it is not meant to be interpreted literally, why not replace the term with the more accurate descriptor? YOLO. :)

**Review by greg0ire — APPROVED** [review]

**Comment by ciaranmcnulty** [comment]
Costs nothing, helps someone feel included, why not?

**Comment by theofidry** [comment]
Fair enough

**Pull request merged**
