### PR TITLE
added StyleCI badge in readme

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You might want to apply the rounded style to it.

**Comment by GrahamCampbell** [comment]
This url: https://img.shields.io/badge/StyleCI-passed-brightgreen.svg?style=flat.

**Comment by GrahamCampbell** [comment]
This url: https://styleci.io/repos/28300862/shield?style=flat.

**Comment by GrahamCampbell** [comment]
[StyleCI](https://styleci.io/repos/28300862)

**Comment by samsonasik** [comment]
@GrahamCampbell done ;)

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by padraic** [comment]
Merged ;)

**Pull request merged**
