### PR TITLE
Fixes GeneratorTest::testShouldCollateAllFilesValidForMutationTesting()

### PR DESCRIPTION
**Pull request by samsonasik**
as <code>Generate::getMutables()</code> returns array of Mutable objects.

### CODE REVIEW

**Comment by padraic** [comment]
All tests are now running green ;). Finally!

**Comment by samsonasik** [comment]
@padraic it still not work and mine with different error ( i'm using mac ). 
```
$ phpunit
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from /Users/samsonasik/www/humbug/phpunit.xml.dist

.......F.......................................................  63 / 102 ( 61%)
.......................................

Time: 1.79 seconds, Memory: 12.25Mb

There was 1 failure:

1) Humbug\Test\GeneratorTest::testShouldCollateAllFilesValidForMutationTesting
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/Users/samsonasik/www/humbug/tests/Humbug/Test/_files/root/base1/library/bool1.php'
+'/Users/samsonasik/www/humbug/tests/Humbug/Test/_files/root/base1/library/bool2.php'

/Users/samsonasik/www/humbug/tests/Humbug/Test/GeneratorTest.php:42
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
                                         
FAILURES!                                
Tests: 102, Assertions: 139, Failures: 1.
```

**Comment by padraic** [comment]
Hmm, we need to just split this out into something that's not order specific like two contains using your original variation of checking against the object instance (whereas my version is on the file name).

**Comment by samsonasik** [comment]
@padraic yes, travis build still failure too...

**Comment by padraic** [comment]
@samsonasik Seems to be a travis.yml bug pointing phpunit at tests/ instead of letting it run in the base directory. Fixed it now so should have a passing build in a while.

**Pull request closed without merging**
