### PR TITLE
add missing functions in Generator class

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by padraic** [comment]
I think this might be the case of the tests being wrong - we don't currently use any of these methods so another means of testing Generator would be preferable.

**Comment by samsonasik** [comment]
what your suggestion on it ?

**Comment by samsonasik** [comment]
rebased, added back 'setSourceDirectory' as it used in Container

**Comment by samsonasik** [comment]
@padraic any something i can do on this ? or close it ?

**Pull request closed without merging**
