### PR TITLE
Allow for newer phpunit versions

### PR DESCRIPTION
**Pull request by shadowhand**
To work with global installations of PHPUnit 5+

### CODE REVIEW

**Comment by shadowhand** [comment]
Something weird is going on with that build... every single version seems to have failed simply by changing versions. That shouldn't happen.

**Comment by MarkRedeman** [comment]
@shadowhand it's due to a bug in PHPUnit. See #158, #162. The current version of Humbug is unstable because PHPUnit introduced a bug between 4.7 and 4.8.

**Comment by padraic** [comment]
Is there any crossover here with https://github.com/padraic/humbug/pull/162???

**Comment by MarkRedeman** [comment]
#162 only fixed a bug in PHPUnit 4.8 that is also present in 5.*.

It should be safe to merge this PR (either now, or once it's rebased so that travis can check it), however [padraic/phpunit-extensions](https://github.com/padraic/phpunit-extensions/blob/master/composer.json) requires `~4.0` so that should also be updated.

**Comment by padraic** [comment]
I've tagged a new version of the extensions also.

**Comment by padraic** [comment]
All checks now passing.

**Pull request merged**
