### PR TITLE
Configure command

### PR DESCRIPTION
**Pull request by rollenes**
This is first part of #126.
Running this is possible with `humbug configure` via CLI.
To merge it requires: 
* upgrade with texts and colors displayed to user - I hope to get some help with texts as I`m good with user experience
* update of README.md
* optional is to move tests to behat scenarios. As it would increase readability of those tests. If it is not in this PR I`ll move it to second part of #126

Please don`t merge before texts are OK.

### CODE REVIEW

**Comment by padraic** [comment]
Thanks @rollenes, will check it out tomorrow evening and help with the text elements if needed.

Yes, behat scenarios would be the preference now that the basic setup is in place. If adding, implement any when/given/then phrasing you need (not a lot there at the moment since there's just the --version feature).

**Comment by padraic** [comment]
Note: I have gotten around to reverting the weekend commits. This should bring Humbug back to working state while I wrap up bug fixing in a separate branch. Composer update and rebase as needed.

**Comment by padraic** [comment]
@rollenes Added a PR for a few text changes. Colors are currently done manually (there are no custom formats for Humbug right now). So the usual `<fg=red>text</fg=red>` pattern works with most colours.

**Comment by padraic** [comment]
@rollenes I'm happy to merge if you are? Behat and colouring are not critical holdups and can be done as separate improvements.

**Comment by rollenes** [comment]
Ok. You can merge. I`ll prepare improvements as separate PR.

**Comment by padraic** [comment]
Thanks again @rollenes!

**Pull request merged**
